### ISSUE TITLE
Add more algorithms in c++/java (Hacktoberfest 2020)

### ISSUE THREAD

**Issue by ng29** [ng29/My-Codes#57]
Hola guyz,

Add more algorithmic questions and leetcode solutions to this repo, just maintain the hierarchy .
And commit in language folder wise.

Just raise a PR and i will merge 👍 

Cheers

**Comment by ankan10** [comment]
Can I work on this?

**Comment by efguydan** [comment]
Can i work on this?

**Comment by ng29** [comment]
Sure @ankan10  and @efguydan  go for it

**Comment by ankan10** [comment]
I want to add all possible mathematical problems, well coded and solved in three ways that is naive, efficient and optimized. Will it be fine?

**Comment by ng29** [comment]
> I want to add all possible mathematical problems, well coded and solved in three ways that is naive, efficient and optimized. Will it be fine?

Sure @ankan10

**Comment by ankan10** [comment]
I added please check :)

**Comment by efguydan** [comment]
I added some leetcode solutions with PR #65. Kindly help check, Thank you.

**Comment by DivyaSaravanan** [comment]
Can I work on questions based on Graphs ? @ng29

**Comment by ng29** [comment]
> Can I work on questions based on Graphs ? @ng29

Go for it @DivyaSaravanan

**Comment by Suman5501** [comment]
Can I add another solution for any solved problem in the repos? @ng29

**Comment by DivyaSaravanan** [comment]
@ng29  Can you check my PR #69  ?

**Comment by ng29** [comment]
done
